### PR TITLE
WIP: Will create an updated _sysconfigdata.py module as part of install.

### PR DESCRIPTION
**Pull request by joakim-hove**
This will update the `_sysconfigdata.py` module with actual values for `prefix` and `exec-prefix`. Will fire of a test on 'bleeding' to see if it works at all.

I know it aint pretty ;-(

### CODE REVIEW

**Comment by joakim-hove** [comment]
> Will fire of a test on 'bleeding' to see if it works at all.

Ehhh - that was not so simple; will let this dangle here for now - but hope we can merge something along this direction.

**Comment by joakim-hove** [comment]
OK - have built this as *bleeding* now - superficially seems to work.

**Comment by pgdr** [comment]
Will you let me know if you need anything from me on this issue?

**Comment by joakim-hove** [comment]
> Will you let me know if you need anything from me on this issue?

Thank - I am doing laps on Jenkins; all the time thinking "Now it will work". If you have opinions on the general approach - which has admittedly been a bit in flux - I am happy to hear,

**Pull request closed without merging**
